///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

use num_enum::{ IntoPrimitive, TryFromPrimitive };
use serde_repr::{ Serialize_repr, Deserialize_repr };
use strum_macros::{ EnumString, EnumIter, Display, AsRefStr, IntoStaticStr };

/// League of Legend's champions.
///
/// The documentation of each variant specifies:<br>
/// NAME (`IDENTIFIER`, ID).
///
/// Implements [IntoEnumIterator](super::IntoEnumIterator).
#[cfg_attr(feature = "nightly", non_exhaustive)]
#[derive(Debug, Copy, Clone)]
#[derive(IntoPrimitive, TryFromPrimitive)]
#[derive(Serialize_repr, Deserialize_repr)]
#[derive(EnumString, EnumIter, Display, AsRefStr, IntoStaticStr)]
#[repr(i16)]
pub enum Champion {
    /// A champion that doesn't exist. Used in TeamBans when no champion was banned.
    ///
    /// None (`NONE`, -1).
    None = -1,

    /// Aatrox (`Aatrox`, 266).
    #[strum(to_string="Aatrox", serialize="Aatrox")] Aatrox = 266,
    /// Ahri (`Ahri`, 103).
    #[strum(to_string="Ahri", serialize="Ahri")] Ahri = 103,
    /// Akali (`Akali`, 84).
    #[strum(to_string="Akali", serialize="Akali")] Akali = 84,
    /// Alistar (`Alistar`, 12).
    #[strum(to_string="Alistar", serialize="Alistar")] Alistar = 12,
    /// Amumu (`Amumu`, 32).
    #[strum(to_string="Amumu", serialize="Amumu")] Amumu = 32,
    /// Anivia (`Anivia`, 34).
    #[strum(to_string="Anivia", serialize="Anivia")] Anivia = 34,
    /// Annie (`Annie`, 1).
    #[strum(to_string="Annie", serialize="Annie")] Annie = 1,
    /// Aphelios (`Aphelios`, 523).
    #[strum(to_string="Aphelios", serialize="Aphelios")] Aphelios = 523,
    /// Ashe (`Ashe`, 22).
    #[strum(to_string="Ashe", serialize="Ashe")] Ashe = 22,
    /// Aurelion Sol (`AurelionSol`, 136).
    #[strum(to_string="Aurelion Sol", serialize="AurelionSol")] AurelionSol = 136,
    /// Azir (`Azir`, 268).
    #[strum(to_string="Azir", serialize="Azir")] Azir = 268,
    /// Bard (`Bard`, 432).
    #[strum(to_string="Bard", serialize="Bard")] Bard = 432,
    /// Blitzcrank (`Blitzcrank`, 53).
    #[strum(to_string="Blitzcrank", serialize="Blitzcrank")] Blitzcrank = 53,
    /// Brand (`Brand`, 63).
    #[strum(to_string="Brand", serialize="Brand")] Brand = 63,
    /// Braum (`Braum`, 201).
    #[strum(to_string="Braum", serialize="Braum")] Braum = 201,
    /// Caitlyn (`Caitlyn`, 51).
    #[strum(to_string="Caitlyn", serialize="Caitlyn")] Caitlyn = 51,
    /// Camille (`Camille`, 164).
    #[strum(to_string="Camille", serialize="Camille")] Camille = 164,
    /// Cassiopeia (`Cassiopeia`, 69).
    #[strum(to_string="Cassiopeia", serialize="Cassiopeia")] Cassiopeia = 69,
    /// Cho'Gath (`Chogath`, 31).
    #[strum(to_string="Cho'Gath", serialize="Chogath")] ChoGath = 31,
    /// Corki (`Corki`, 42).
    #[strum(to_string="Corki", serialize="Corki")] Corki = 42,
    /// Darius (`Darius`, 122).
    #[strum(to_string="Darius", serialize="Darius")] Darius = 122,
    /// Diana (`Diana`, 131).
    #[strum(to_string="Diana", serialize="Diana")] Diana = 131,
    /// Dr. Mundo (`DrMundo`, 36).
    #[strum(to_string="Dr. Mundo", serialize="DrMundo")] DrMundo = 36,
    /// Draven (`Draven`, 119).
    #[strum(to_string="Draven", serialize="Draven")] Draven = 119,
    /// Ekko (`Ekko`, 245).
    #[strum(to_string="Ekko", serialize="Ekko")] Ekko = 245,
    /// Elise (`Elise`, 60).
    #[strum(to_string="Elise", serialize="Elise")] Elise = 60,
    /// Evelynn (`Evelynn`, 28).
    #[strum(to_string="Evelynn", serialize="Evelynn")] Evelynn = 28,
    /// Ezreal (`Ezreal`, 81).
    #[strum(to_string="Ezreal", serialize="Ezreal")] Ezreal = 81,
    /// Fiddlesticks (`FiddleSticks`, 9).
    #[strum(to_string="Fiddlesticks", serialize="FiddleSticks")] Fiddlesticks = 9,
    /// Fiora (`Fiora`, 114).
    #[strum(to_string="Fiora", serialize="Fiora")] Fiora = 114,
    /// Fizz (`Fizz`, 105).
    #[strum(to_string="Fizz", serialize="Fizz")] Fizz = 105,
    /// Galio (`Galio`, 3).
    #[strum(to_string="Galio", serialize="Galio")] Galio = 3,
    /// Gangplank (`Gangplank`, 41).
    #[strum(to_string="Gangplank", serialize="Gangplank")] Gangplank = 41,
    /// Garen (`Garen`, 86).
    #[strum(to_string="Garen", serialize="Garen")] Garen = 86,
    /// Gnar (`Gnar`, 150).
    #[strum(to_string="Gnar", serialize="Gnar")] Gnar = 150,
    /// Gragas (`Gragas`, 79).
    #[strum(to_string="Gragas", serialize="Gragas")] Gragas = 79,
    /// Graves (`Graves`, 104).
    #[strum(to_string="Graves", serialize="Graves")] Graves = 104,
    /// Hecarim (`Hecarim`, 120).
    #[strum(to_string="Hecarim", serialize="Hecarim")] Hecarim = 120,
    /// Heimerdinger (`Heimerdinger`, 74).
    #[strum(to_string="Heimerdinger", serialize="Heimerdinger")] Heimerdinger = 74,
    /// Illaoi (`Illaoi`, 420).
    #[strum(to_string="Illaoi", serialize="Illaoi")] Illaoi = 420,
    /// Irelia (`Irelia`, 39).
    #[strum(to_string="Irelia", serialize="Irelia")] Irelia = 39,
    /// Ivern (`Ivern`, 427).
    #[strum(to_string="Ivern", serialize="Ivern")] Ivern = 427,
    /// Janna (`Janna`, 40).
    #[strum(to_string="Janna", serialize="Janna")] Janna = 40,
    /// Jarvan IV (`JarvanIV`, 59).
    #[strum(to_string="Jarvan IV", serialize="JarvanIV")] JarvanIV = 59,
    /// Jax (`Jax`, 24).
    #[strum(to_string="Jax", serialize="Jax")] Jax = 24,
    /// Jayce (`Jayce`, 126).
    #[strum(to_string="Jayce", serialize="Jayce")] Jayce = 126,
    /// Jhin (`Jhin`, 202).
    #[strum(to_string="Jhin", serialize="Jhin")] Jhin = 202,
    /// Jinx (`Jinx`, 222).
    #[strum(to_string="Jinx", serialize="Jinx")] Jinx = 222,
    /// Kai'Sa (`Kaisa`, 145).
    #[strum(to_string="Kai'Sa", serialize="Kaisa")] KaiSa = 145,
    /// Kalista (`Kalista`, 429).
    #[strum(to_string="Kalista", serialize="Kalista")] Kalista = 429,
    /// Karma (`Karma`, 43).
    #[strum(to_string="Karma", serialize="Karma")] Karma = 43,
    /// Karthus (`Karthus`, 30).
    #[strum(to_string="Karthus", serialize="Karthus")] Karthus = 30,
    /// Kassadin (`Kassadin`, 38).
    #[strum(to_string="Kassadin", serialize="Kassadin")] Kassadin = 38,
    /// Katarina (`Katarina`, 55).
    #[strum(to_string="Katarina", serialize="Katarina")] Katarina = 55,
    /// Kayle (`Kayle`, 10).
    #[strum(to_string="Kayle", serialize="Kayle")] Kayle = 10,
    /// Kayn (`Kayn`, 141).
    #[strum(to_string="Kayn", serialize="Kayn")] Kayn = 141,
    /// Kennen (`Kennen`, 85).
    #[strum(to_string="Kennen", serialize="Kennen")] Kennen = 85,
    /// Kha'Zix (`Khazix`, 121).
    #[strum(to_string="Kha'Zix", serialize="Khazix")] KhaZix = 121,
    /// Kindred (`Kindred`, 203).
    #[strum(to_string="Kindred", serialize="Kindred")] Kindred = 203,
    /// Kled (`Kled`, 240).
    #[strum(to_string="Kled", serialize="Kled")] Kled = 240,
    /// Kog'Maw (`KogMaw`, 96).
    #[strum(to_string="Kog'Maw", serialize="KogMaw")] KogMaw = 96,
    /// LeBlanc (`Leblanc`, 7).
    #[strum(to_string="LeBlanc", serialize="Leblanc")] LeBlanc = 7,
    /// Lee Sin (`LeeSin`, 64).
    #[strum(to_string="Lee Sin", serialize="LeeSin")] LeeSin = 64,
    /// Leona (`Leona`, 89).
    #[strum(to_string="Leona", serialize="Leona")] Leona = 89,
    /// Lillia (`Lillia`, 876).
    #[strum(to_string="Lillia", serialize="Lillia")] Lillia = 876,
    /// Lissandra (`Lissandra`, 127).
    #[strum(to_string="Lissandra", serialize="Lissandra")] Lissandra = 127,
    /// Lucian (`Lucian`, 236).
    #[strum(to_string="Lucian", serialize="Lucian")] Lucian = 236,
    /// Lulu (`Lulu`, 117).
    #[strum(to_string="Lulu", serialize="Lulu")] Lulu = 117,
    /// Lux (`Lux`, 99).
    #[strum(to_string="Lux", serialize="Lux")] Lux = 99,
    /// Malphite (`Malphite`, 54).
    #[strum(to_string="Malphite", serialize="Malphite")] Malphite = 54,
    /// Malzahar (`Malzahar`, 90).
    #[strum(to_string="Malzahar", serialize="Malzahar")] Malzahar = 90,
    /// Maokai (`Maokai`, 57).
    #[strum(to_string="Maokai", serialize="Maokai")] Maokai = 57,
    /// Master Yi (`MasterYi`, 11).
    #[strum(to_string="Master Yi", serialize="MasterYi")] MasterYi = 11,
    /// Miss Fortune (`MissFortune`, 21).
    #[strum(to_string="Miss Fortune", serialize="MissFortune")] MissFortune = 21,
    /// Mordekaiser (`Mordekaiser`, 82).
    #[strum(to_string="Mordekaiser", serialize="Mordekaiser")] Mordekaiser = 82,
    /// Morgana (`Morgana`, 25).
    #[strum(to_string="Morgana", serialize="Morgana")] Morgana = 25,
    /// Nami (`Nami`, 267).
    #[strum(to_string="Nami", serialize="Nami")] Nami = 267,
    /// Nasus (`Nasus`, 75).
    #[strum(to_string="Nasus", serialize="Nasus")] Nasus = 75,
    /// Nautilus (`Nautilus`, 111).
    #[strum(to_string="Nautilus", serialize="Nautilus")] Nautilus = 111,
    /// Neeko (`Neeko`, 518).
    #[strum(to_string="Neeko", serialize="Neeko")] Neeko = 518,
    /// Nidalee (`Nidalee`, 76).
    #[strum(to_string="Nidalee", serialize="Nidalee")] Nidalee = 76,
    /// Nocturne (`Nocturne`, 56).
    #[strum(to_string="Nocturne", serialize="Nocturne")] Nocturne = 56,
    /// Nunu & Willump (`Nunu`, 20).
    #[strum(to_string="Nunu & Willump", serialize="Nunu")] NunuWillump = 20,
    /// Olaf (`Olaf`, 2).
    #[strum(to_string="Olaf", serialize="Olaf")] Olaf = 2,
    /// Orianna (`Orianna`, 61).
    #[strum(to_string="Orianna", serialize="Orianna")] Orianna = 61,
    /// Ornn (`Ornn`, 516).
    #[strum(to_string="Ornn", serialize="Ornn")] Ornn = 516,
    /// Pantheon (`Pantheon`, 80).
    #[strum(to_string="Pantheon", serialize="Pantheon")] Pantheon = 80,
    /// Poppy (`Poppy`, 78).
    #[strum(to_string="Poppy", serialize="Poppy")] Poppy = 78,
    /// Pyke (`Pyke`, 555).
    #[strum(to_string="Pyke", serialize="Pyke")] Pyke = 555,
    /// Qiyana (`Qiyana`, 246).
    #[strum(to_string="Qiyana", serialize="Qiyana")] Qiyana = 246,
    /// Quinn (`Quinn`, 133).
    #[strum(to_string="Quinn", serialize="Quinn")] Quinn = 133,
    /// Rakan (`Rakan`, 497).
    #[strum(to_string="Rakan", serialize="Rakan")] Rakan = 497,
    /// Rammus (`Rammus`, 33).
    #[strum(to_string="Rammus", serialize="Rammus")] Rammus = 33,
    /// Rek'Sai (`RekSai`, 421).
    #[strum(to_string="Rek'Sai", serialize="RekSai")] RekSai = 421,
    /// Renekton (`Renekton`, 58).
    #[strum(to_string="Renekton", serialize="Renekton")] Renekton = 58,
    /// Rengar (`Rengar`, 107).
    #[strum(to_string="Rengar", serialize="Rengar")] Rengar = 107,
    /// Riven (`Riven`, 92).
    #[strum(to_string="Riven", serialize="Riven")] Riven = 92,
    /// Rumble (`Rumble`, 68).
    #[strum(to_string="Rumble", serialize="Rumble")] Rumble = 68,
    /// Ryze (`Ryze`, 13).
    #[strum(to_string="Ryze", serialize="Ryze")] Ryze = 13,
    /// Samira (`Samira`, 360).
    #[strum(to_string="Samira", serialize="Samira")] Samira = 360,
    /// Sejuani (`Sejuani`, 113).
    #[strum(to_string="Sejuani", serialize="Sejuani")] Sejuani = 113,
    /// Senna (`Senna`, 235).
    #[strum(to_string="Senna", serialize="Senna")] Senna = 235,
    /// Seraphine (`Seraphine`, 147).
    #[strum(to_string="Seraphine", serialize="Seraphine")] Seraphine = 147,
    /// Sett (`Sett`, 875).
    #[strum(to_string="Sett", serialize="Sett")] Sett = 875,
    /// Shaco (`Shaco`, 35).
    #[strum(to_string="Shaco", serialize="Shaco")] Shaco = 35,
    /// Shen (`Shen`, 98).
    #[strum(to_string="Shen", serialize="Shen")] Shen = 98,
    /// Shyvana (`Shyvana`, 102).
    #[strum(to_string="Shyvana", serialize="Shyvana")] Shyvana = 102,
    /// Singed (`Singed`, 27).
    #[strum(to_string="Singed", serialize="Singed")] Singed = 27,
    /// Sion (`Sion`, 14).
    #[strum(to_string="Sion", serialize="Sion")] Sion = 14,
    /// Sivir (`Sivir`, 15).
    #[strum(to_string="Sivir", serialize="Sivir")] Sivir = 15,
    /// Skarner (`Skarner`, 72).
    #[strum(to_string="Skarner", serialize="Skarner")] Skarner = 72,
    /// Sona (`Sona`, 37).
    #[strum(to_string="Sona", serialize="Sona")] Sona = 37,
    /// Soraka (`Soraka`, 16).
    #[strum(to_string="Soraka", serialize="Soraka")] Soraka = 16,
    /// Swain (`Swain`, 50).
    #[strum(to_string="Swain", serialize="Swain")] Swain = 50,
    /// Sylas (`Sylas`, 517).
    #[strum(to_string="Sylas", serialize="Sylas")] Sylas = 517,
    /// Syndra (`Syndra`, 134).
    #[strum(to_string="Syndra", serialize="Syndra")] Syndra = 134,
    /// Tahm Kench (`TahmKench`, 223).
    #[strum(to_string="Tahm Kench", serialize="TahmKench")] TahmKench = 223,
    /// Taliyah (`Taliyah`, 163).
    #[strum(to_string="Taliyah", serialize="Taliyah")] Taliyah = 163,
    /// Talon (`Talon`, 91).
    #[strum(to_string="Talon", serialize="Talon")] Talon = 91,
    /// Taric (`Taric`, 44).
    #[strum(to_string="Taric", serialize="Taric")] Taric = 44,
    /// Teemo (`Teemo`, 17).
    #[strum(to_string="Teemo", serialize="Teemo")] Teemo = 17,
    /// Thresh (`Thresh`, 412).
    #[strum(to_string="Thresh", serialize="Thresh")] Thresh = 412,
    /// Tristana (`Tristana`, 18).
    #[strum(to_string="Tristana", serialize="Tristana")] Tristana = 18,
    /// Trundle (`Trundle`, 48).
    #[strum(to_string="Trundle", serialize="Trundle")] Trundle = 48,
    /// Tryndamere (`Tryndamere`, 23).
    #[strum(to_string="Tryndamere", serialize="Tryndamere")] Tryndamere = 23,
    /// Twisted Fate (`TwistedFate`, 4).
    #[strum(to_string="Twisted Fate", serialize="TwistedFate")] TwistedFate = 4,
    /// Twitch (`Twitch`, 29).
    #[strum(to_string="Twitch", serialize="Twitch")] Twitch = 29,
    /// Udyr (`Udyr`, 77).
    #[strum(to_string="Udyr", serialize="Udyr")] Udyr = 77,
    /// Urgot (`Urgot`, 6).
    #[strum(to_string="Urgot", serialize="Urgot")] Urgot = 6,
    /// Varus (`Varus`, 110).
    #[strum(to_string="Varus", serialize="Varus")] Varus = 110,
    /// Vayne (`Vayne`, 67).
    #[strum(to_string="Vayne", serialize="Vayne")] Vayne = 67,
    /// Veigar (`Veigar`, 45).
    #[strum(to_string="Veigar", serialize="Veigar")] Veigar = 45,
    /// Vel'Koz (`Velkoz`, 161).
    #[strum(to_string="Vel'Koz", serialize="Velkoz")] VelKoz = 161,
    /// Vi (`Vi`, 254).
    #[strum(to_string="Vi", serialize="Vi")] Vi = 254,
    /// Viktor (`Viktor`, 112).
    #[strum(to_string="Viktor", serialize="Viktor")] Viktor = 112,
    /// Vladimir (`Vladimir`, 8).
    #[strum(to_string="Vladimir", serialize="Vladimir")] Vladimir = 8,
    /// Volibear (`Volibear`, 106).
    #[strum(to_string="Volibear", serialize="Volibear")] Volibear = 106,
    /// Warwick (`Warwick`, 19).
    #[strum(to_string="Warwick", serialize="Warwick")] Warwick = 19,
    /// Wukong (`MonkeyKing`, 62).
    #[strum(to_string="Wukong", serialize="MonkeyKing")] Wukong = 62,
    /// Xayah (`Xayah`, 498).
    #[strum(to_string="Xayah", serialize="Xayah")] Xayah = 498,
    /// Xerath (`Xerath`, 101).
    #[strum(to_string="Xerath", serialize="Xerath")] Xerath = 101,
    /// Xin Zhao (`XinZhao`, 5).
    #[strum(to_string="Xin Zhao", serialize="XinZhao")] XinZhao = 5,
    /// Yasuo (`Yasuo`, 157).
    #[strum(to_string="Yasuo", serialize="Yasuo")] Yasuo = 157,
    /// Yone (`Yone`, 777).
    #[strum(to_string="Yone", serialize="Yone")] Yone = 777,
    /// Yorick (`Yorick`, 83).
    #[strum(to_string="Yorick", serialize="Yorick")] Yorick = 83,
    /// Yuumi (`Yuumi`, 350).
    #[strum(to_string="Yuumi", serialize="Yuumi")] Yuumi = 350,
    /// Zac (`Zac`, 154).
    #[strum(to_string="Zac", serialize="Zac")] Zac = 154,
    /// Zed (`Zed`, 238).
    #[strum(to_string="Zed", serialize="Zed")] Zed = 238,
    /// Ziggs (`Ziggs`, 115).
    #[strum(to_string="Ziggs", serialize="Ziggs")] Ziggs = 115,
    /// Zilean (`Zilean`, 26).
    #[strum(to_string="Zilean", serialize="Zilean")] Zilean = 26,
    /// Zoe (`Zoe`, 142).
    #[strum(to_string="Zoe", serialize="Zoe")] Zoe = 142,
    /// Zyra (`Zyra`, 143).
    #[strum(to_string="Zyra", serialize="Zyra")] Zyra = 143,
}

impl Champion {
    /// The champion's name (localized `en_US`), or `"NONE"` for the None variant.
    pub fn name(self) -> &'static str {
        self.into()
    }

    /// The champion's identifier key. Somtimes called "key", "identifier", or "alias".
    /// This is mainly used in DDragon paths.
    ///
    /// This is generally the `en_US` name with spaces and punctuation removed,
    /// but there are the following exceptions:
    ///
    /// Variant | Name | Identifier
    /// --------|------|-----------
    /// `None` | "NONE" | "NONE"
    /// `ChoGath` | "Cho'Gath" | "Chogath"
    /// `Fiddlesticks` | "Fiddlesticks" | "FiddleSticks"
    /// `KaiSa` | "Kai'Sa" | "Kaisa"
    /// `KhaZix` | "Kha'Zix" | "Khazix"
    /// `LeBlanc` | "LeBlanc" | "Leblanc"
    /// `NunuWillump` | "Nunu & Willump" | "Nunu"
    /// `VelKoz` | "Vel'Koz" | "Velkoz"
    /// `Wukong` | "Wukong" | "MonkeyKing"
    pub fn identifier(self) -> &'static str {
        match self {
            Self::None         => "NONE",
            Self::Aatrox       => "Aatrox",
            Self::Ahri         => "Ahri",
            Self::Akali        => "Akali",
            Self::Alistar      => "Alistar",
            Self::Amumu        => "Amumu",
            Self::Anivia       => "Anivia",
            Self::Annie        => "Annie",
            Self::Aphelios     => "Aphelios",
            Self::Ashe         => "Ashe",
            Self::AurelionSol  => "AurelionSol",
            Self::Azir         => "Azir",
            Self::Bard         => "Bard",
            Self::Blitzcrank   => "Blitzcrank",
            Self::Brand        => "Brand",
            Self::Braum        => "Braum",
            Self::Caitlyn      => "Caitlyn",
            Self::Camille      => "Camille",
            Self::Cassiopeia   => "Cassiopeia",
            Self::ChoGath      => "Chogath",
            Self::Corki        => "Corki",
            Self::Darius       => "Darius",
            Self::Diana        => "Diana",
            Self::DrMundo      => "DrMundo",
            Self::Draven       => "Draven",
            Self::Ekko         => "Ekko",
            Self::Elise        => "Elise",
            Self::Evelynn      => "Evelynn",
            Self::Ezreal       => "Ezreal",
            Self::Fiddlesticks => "FiddleSticks",
            Self::Fiora        => "Fiora",
            Self::Fizz         => "Fizz",
            Self::Galio        => "Galio",
            Self::Gangplank    => "Gangplank",
            Self::Garen        => "Garen",
            Self::Gnar         => "Gnar",
            Self::Gragas       => "Gragas",
            Self::Graves       => "Graves",
            Self::Hecarim      => "Hecarim",
            Self::Heimerdinger => "Heimerdinger",
            Self::Illaoi       => "Illaoi",
            Self::Irelia       => "Irelia",
            Self::Ivern        => "Ivern",
            Self::Janna        => "Janna",
            Self::JarvanIV     => "JarvanIV",
            Self::Jax          => "Jax",
            Self::Jayce        => "Jayce",
            Self::Jhin         => "Jhin",
            Self::Jinx         => "Jinx",
            Self::KaiSa        => "Kaisa",
            Self::Kalista      => "Kalista",
            Self::Karma        => "Karma",
            Self::Karthus      => "Karthus",
            Self::Kassadin     => "Kassadin",
            Self::Katarina     => "Katarina",
            Self::Kayle        => "Kayle",
            Self::Kayn         => "Kayn",
            Self::Kennen       => "Kennen",
            Self::KhaZix       => "Khazix",
            Self::Kindred      => "Kindred",
            Self::Kled         => "Kled",
            Self::KogMaw       => "KogMaw",
            Self::LeBlanc      => "Leblanc",
            Self::LeeSin       => "LeeSin",
            Self::Leona        => "Leona",
            Self::Lillia       => "Lillia",
            Self::Lissandra    => "Lissandra",
            Self::Lucian       => "Lucian",
            Self::Lulu         => "Lulu",
            Self::Lux          => "Lux",
            Self::Malphite     => "Malphite",
            Self::Malzahar     => "Malzahar",
            Self::Maokai       => "Maokai",
            Self::MasterYi     => "MasterYi",
            Self::MissFortune  => "MissFortune",
            Self::Mordekaiser  => "Mordekaiser",
            Self::Morgana      => "Morgana",
            Self::Nami         => "Nami",
            Self::Nasus        => "Nasus",
            Self::Nautilus     => "Nautilus",
            Self::Neeko        => "Neeko",
            Self::Nidalee      => "Nidalee",
            Self::Nocturne     => "Nocturne",
            Self::NunuWillump  => "Nunu",
            Self::Olaf         => "Olaf",
            Self::Orianna      => "Orianna",
            Self::Ornn         => "Ornn",
            Self::Pantheon     => "Pantheon",
            Self::Poppy        => "Poppy",
            Self::Pyke         => "Pyke",
            Self::Qiyana       => "Qiyana",
            Self::Quinn        => "Quinn",
            Self::Rakan        => "Rakan",
            Self::Rammus       => "Rammus",
            Self::RekSai       => "RekSai",
            Self::Renekton     => "Renekton",
            Self::Rengar       => "Rengar",
            Self::Riven        => "Riven",
            Self::Rumble       => "Rumble",
            Self::Ryze         => "Ryze",
            Self::Samira       => "Samira",
            Self::Sejuani      => "Sejuani",
            Self::Senna        => "Senna",
            Self::Seraphine    => "Seraphine",
            Self::Sett         => "Sett",
            Self::Shaco        => "Shaco",
            Self::Shen         => "Shen",
            Self::Shyvana      => "Shyvana",
            Self::Singed       => "Singed",
            Self::Sion         => "Sion",
            Self::Sivir        => "Sivir",
            Self::Skarner      => "Skarner",
            Self::Sona         => "Sona",
            Self::Soraka       => "Soraka",
            Self::Swain        => "Swain",
            Self::Sylas        => "Sylas",
            Self::Syndra       => "Syndra",
            Self::TahmKench    => "TahmKench",
            Self::Taliyah      => "Taliyah",
            Self::Talon        => "Talon",
            Self::Taric        => "Taric",
            Self::Teemo        => "Teemo",
            Self::Thresh       => "Thresh",
            Self::Tristana     => "Tristana",
            Self::Trundle      => "Trundle",
            Self::Tryndamere   => "Tryndamere",
            Self::TwistedFate  => "TwistedFate",
            Self::Twitch       => "Twitch",
            Self::Udyr         => "Udyr",
            Self::Urgot        => "Urgot",
            Self::Varus        => "Varus",
            Self::Vayne        => "Vayne",
            Self::Veigar       => "Veigar",
            Self::VelKoz       => "Velkoz",
            Self::Vi           => "Vi",
            Self::Viktor       => "Viktor",
            Self::Vladimir     => "Vladimir",
            Self::Volibear     => "Volibear",
            Self::Warwick      => "Warwick",
            Self::Wukong       => "MonkeyKing",
            Self::Xayah        => "Xayah",
            Self::Xerath       => "Xerath",
            Self::XinZhao      => "XinZhao",
            Self::Yasuo        => "Yasuo",
            Self::Yone         => "Yone",
            Self::Yorick       => "Yorick",
            Self::Yuumi        => "Yuumi",
            Self::Zac          => "Zac",
            Self::Zed          => "Zed",
            Self::Ziggs        => "Ziggs",
            Self::Zilean       => "Zilean",
            Self::Zoe          => "Zoe",
            Self::Zyra         => "Zyra",
        }
    }
}
