// This file is automatically generated.
// Do not directly edit.

use strum_macros::{ EnumString, Display, AsRefStr };

/// League of Legends game mode, such as Classic,
/// ARAM, URF, One For All, Ascension, etc.
#[derive(Debug, Copy, Clone)]
#[derive(Eq, PartialEq, Hash)]
#[derive(EnumString, Display, AsRefStr)]
#[repr(u8)]
pub enum GameMode {
    /// Classic Summoner's Rift and Twisted Treeline games
    #[strum(to_string="CLASSIC")]
    Classic,
    /// Dominion/Crystal Scar games
    #[strum(to_string="ODIN")]
    Odin,
    /// ARAM games
    #[strum(to_string="ARAM")]
    Aram,
    /// Tutorial games
    #[strum(to_string="TUTORIAL")]
    Tutorial,
    /// URF games
    #[strum(to_string="URF")]
    Urf,
    /// Doom Bot games
    #[strum(to_string="DOOMBOTSTEEMO")]
    Doombotsteemo,
    /// One for All games
    #[strum(to_string="ONEFORALL")]
    Oneforall,
    /// Ascension games
    #[strum(to_string="ASCENSION")]
    Ascension,
    /// Snowdown Showdown games
    #[strum(to_string="FIRSTBLOOD")]
    Firstblood,
    /// Legend of the Poro King games
    #[strum(to_string="KINGPORO")]
    Kingporo,
    /// Nexus Siege games
    #[strum(to_string="SIEGE")]
    Siege,
    /// Blood Hunt Assassin games
    #[strum(to_string="ASSASSINATE")]
    Assassinate,
    /// All Random Summoner's Rift games
    #[strum(to_string="ARSR")]
    Arsr,
    /// Dark Star: Singularity games
    #[strum(to_string="DARKSTAR")]
    Darkstar,
    /// Star Guardian Invasion games
    #[strum(to_string="STARGUARDIAN")]
    Starguardian,
    /// PROJECT: Hunters games
    #[strum(to_string="PROJECT")]
    Project,
    /// Nexus Blitz games
    #[strum(to_string="GAMEMODEX")]
    Gamemodex,
    /// Odyssey: Extraction games
    #[strum(to_string="ODYSSEY")]
    Odyssey,
}
