// This file is automatically generated.
// Do not directly edit.

/// League of Legends matchmaking seasons.
#[derive(Debug, Copy, Clone)]
#[derive(Eq, PartialEq, Hash, PartialOrd, Ord)]
#[repr(u8)]
pub enum Season {
    Preseason3    = 0,
    Season3       = 1,
    Preseason2014 = 2,
    Season2014    = 3,
    Preseason2015 = 4,
    Season2015    = 5,
    Preseason2106 = 6,
    Season2016    = 7,
    Preseason2017 = 8,
    Season2017    = 9,
    Preseason2018 = 10,
    Season2018    = 11,
    Preseason2019 = 12,
    Season2019    = 13,
}