#![cfg_attr(rustfmt, rustfmt_skip)]
///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

use serde::{ Serialize, Deserialize };
use strum_macros::{ EnumString, Display, AsRefStr, IntoStaticStr };

/// League of Legends game type: matched game, custom game, or tutorial game.
#[derive(Debug, Copy, Clone)]
#[derive(Eq, PartialEq, Hash)]
#[derive(EnumString, Display, AsRefStr, IntoStaticStr)]
#[derive(Serialize, Deserialize)]
#[repr(u8)]
pub enum GameType {
    /// Custom games
    #[strum(to_string = "CUSTOM_GAME", serialize = "CUSTOM")]
    #[serde(alias = "CUSTOM")]
    CUSTOM_GAME,
    /// all other games
    #[strum(to_string = "MATCHED_GAME", serialize = "MATCHED")]
    #[serde(alias = "MATCHED")]
    MATCHED_GAME,
    /// Tutorial games
    #[strum(to_string = "TUTORIAL_GAME", serialize = "TUTORIAL")]
    #[serde(alias = "TUTORIAL")]
    TUTORIAL_GAME,
}

impl GameType {
    /// https://github.com/RiotGames/developer-relations/issues/898
    pub(crate) fn serialize_empty<S>(
        val: &Option<Self>,
        serializer: S,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::ser::Serializer,
    {
        use serde::ser::Serialize;
        if let Some(val) = val {
            val.serialize(serializer)
        } else {
            "".serialize(serializer)
        }
    }

    /// https://github.com/RiotGames/developer-relations/issues/898
    pub(crate) fn deserialize_empty<'de, D>(
        deserializer: D,
    ) -> Result<Option<Self>, D::Error>
    where
        D: serde::de::Deserializer<'de>,
    {
        use serde::de::IntoDeserializer;
        let opt = Option::<String>::deserialize(deserializer)?;
        match opt.as_deref() {
            None | Some("") => Ok(None),
            Some(s) => Self::deserialize(s.into_deserializer()).map(Some)
        }
    }
}

#[cfg(test)]
mod test;
