#![cfg_attr(any(), rustfmt::skip)]
///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

newtype_enum! {
    /// A League of Legends matchmaking queue.
    pub newtype_enum Queue(u16) {
        /// `0`.
        /// Games on Custom games
        CUSTOM = 0,
        /// `2`.
        /// 5v5 Blind Pick games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 430
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 430")]
        SUMMONERS_RIFT_5V5_BLIND_PICK_DEPRECATED_2 = 2,
        /// `4`.
        /// 5v5 Ranked Solo games on Summoner's Rift
        ///
        /// Deprecated in favor of queueId 420
        #[deprecated(note="Deprecated in favor of queueId 420")]
        SUMMONERS_RIFT_5V5_RANKED_SOLO_DEPRECATED_4 = 4,
        /// `6`.
        /// 5v5 Ranked Premade games on Summoner's Rift
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        SUMMONERS_RIFT_5V5_RANKED_PREMADE = 6,
        /// `7`.
        /// Co-op vs AI games on Summoner's Rift
        ///
        /// Deprecated in favor of queueId 32 and 33
        #[deprecated(note="Deprecated in favor of queueId 32 and 33")]
        SUMMONERS_RIFT_CO_OP_VS_AI = 7,
        /// `8`.
        /// 3v3 Normal games on Twisted Treeline
        ///
        /// Deprecated in patch 7.19 in favor of queueId 460
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 460")]
        TWISTED_TREELINE_3V3_NORMAL = 8,
        /// `9`.
        /// 3v3 Ranked Flex games on Twisted Treeline
        ///
        /// Deprecated in patch 7.19 in favor of queueId 470
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 470")]
        TWISTED_TREELINE_3V3_RANKED_FLEX_DEPRECATED_9 = 9,
        /// `14`.
        /// 5v5 Draft Pick games on Summoner's Rift
        ///
        /// Deprecated in favor of queueId 400
        #[deprecated(note="Deprecated in favor of queueId 400")]
        SUMMONERS_RIFT_5V5_DRAFT_PICK_DEPRECATED_14 = 14,
        /// `16`.
        /// 5v5 Dominion Blind Pick games on Crystal Scar
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        CRYSTAL_SCAR_5V5_DOMINION_BLIND_PICK = 16,
        /// `17`.
        /// 5v5 Dominion Draft Pick games on Crystal Scar
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        CRYSTAL_SCAR_5V5_DOMINION_DRAFT_PICK = 17,
        /// `25`.
        /// Dominion Co-op vs AI games on Crystal Scar
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        CRYSTAL_SCAR_DOMINION_CO_OP_VS_AI = 25,
        /// `31`.
        /// Co-op vs AI Intro Bot games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 830
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 830")]
        SUMMONERS_RIFT_CO_OP_VS_AI_INTRO_BOT_DEPRECATED_31 = 31,
        /// `32`.
        /// Co-op vs AI Beginner Bot games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 840
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 840")]
        SUMMONERS_RIFT_CO_OP_VS_AI_BEGINNER_BOT_DEPRECATED_32 = 32,
        /// `33`.
        /// Co-op vs AI Intermediate Bot games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 850
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 850")]
        SUMMONERS_RIFT_CO_OP_VS_AI_INTERMEDIATE_BOT_DEPRECATED_33 = 33,
        /// `41`.
        /// 3v3 Ranked Team games on Twisted Treeline
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        TWISTED_TREELINE_3V3_RANKED_TEAM = 41,
        /// `42`.
        /// 5v5 Ranked Team games on Summoner's Rift
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        SUMMONERS_RIFT_5V5_RANKED_TEAM = 42,
        /// `52`.
        /// Co-op vs AI games on Twisted Treeline
        ///
        /// Deprecated in patch 7.19 in favor of queueId 800
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 800")]
        TWISTED_TREELINE_CO_OP_VS_AI = 52,
        /// `61`.
        /// 5v5 Team Builder games on Summoner's Rift
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        SUMMONERS_RIFT_5V5_TEAM_BUILDER = 61,
        /// `65`.
        /// 5v5 ARAM games on Howling Abyss
        ///
        /// Deprecated in patch 7.19 in favor of queueId 450
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 450")]
        HOWLING_ABYSS_5V5_ARAM_DEPRECATED_65 = 65,
        /// `67`.
        /// ARAM Co-op vs AI games on Howling Abyss
        ///
        /// Game mode deprecated
        #[deprecated(note="Game mode deprecated")]
        HOWLING_ABYSS_ARAM_CO_OP_VS_AI = 67,
        /// `70`.
        /// One for All games on Summoner's Rift
        ///
        /// Deprecated in patch 8.6 in favor of queueId 1020
        #[deprecated(note="Deprecated in patch 8.6 in favor of queueId 1020")]
        SUMMONERS_RIFT_ONE_FOR_ALL_DEPRECATED_70 = 70,
        /// `72`.
        /// 1v1 Snowdown Showdown games on Howling Abyss
        HOWLING_ABYSS_1V1_SNOWDOWN_SHOWDOWN = 72,
        /// `73`.
        /// 2v2 Snowdown Showdown games on Howling Abyss
        HOWLING_ABYSS_2V2_SNOWDOWN_SHOWDOWN = 73,
        /// `75`.
        /// 6v6 Hexakill games on Summoner's Rift
        SUMMONERS_RIFT_6V6_HEXAKILL = 75,
        /// `76`.
        /// Ultra Rapid Fire games on Summoner's Rift
        SUMMONERS_RIFT_ULTRA_RAPID_FIRE = 76,
        /// `78`.
        /// One For All: Mirror Mode games on Howling Abyss
        HOWLING_ABYSS_ONE_FOR_ALL_MIRROR_MODE = 78,
        /// `83`.
        /// Co-op vs AI Ultra Rapid Fire games on Summoner's Rift
        SUMMONERS_RIFT_CO_OP_VS_AI_ULTRA_RAPID_FIRE = 83,
        /// `91`.
        /// Doom Bots Rank 1 games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 950
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 950")]
        SUMMONERS_RIFT_DOOM_BOTS_RANK_1 = 91,
        /// `92`.
        /// Doom Bots Rank 2 games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 950
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 950")]
        SUMMONERS_RIFT_DOOM_BOTS_RANK_2 = 92,
        /// `93`.
        /// Doom Bots Rank 5 games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 950
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 950")]
        SUMMONERS_RIFT_DOOM_BOTS_RANK_5 = 93,
        /// `96`.
        /// Ascension games on Crystal Scar
        ///
        /// Deprecated in patch 7.19 in favor of queueId 910
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 910")]
        CRYSTAL_SCAR_ASCENSION_DEPRECATED_96 = 96,
        /// `98`.
        /// 6v6 Hexakill games on Twisted Treeline
        TWISTED_TREELINE_6V6_HEXAKILL = 98,
        /// `100`.
        /// 5v5 ARAM games on Butcher's Bridge
        BUTCHERS_BRIDGE_5V5_ARAM = 100,
        /// `300`.
        /// Legend of the Poro King games on Howling Abyss
        ///
        /// Deprecated in patch 7.19 in favor of queueId 920
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 920")]
        HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING_DEPRECATED_300 = 300,
        /// `310`.
        /// Nemesis games on Summoner's Rift
        SUMMONERS_RIFT_NEMESIS = 310,
        /// `313`.
        /// Black Market Brawlers games on Summoner's Rift
        SUMMONERS_RIFT_BLACK_MARKET_BRAWLERS = 313,
        /// `315`.
        /// Nexus Siege games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 940
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 940")]
        SUMMONERS_RIFT_NEXUS_SIEGE_DEPRECATED_315 = 315,
        /// `317`.
        /// Definitely Not Dominion games on Crystal Scar
        CRYSTAL_SCAR_DEFINITELY_NOT_DOMINION = 317,
        /// `318`.
        /// ARURF games on Summoner's Rift
        ///
        /// Deprecated in patch 7.19 in favor of queueId 900
        #[deprecated(note="Deprecated in patch 7.19 in favor of queueId 900")]
        SUMMONERS_RIFT_ARURF_DEPRECATED_318 = 318,
        /// `325`.
        /// All Random games on Summoner's Rift
        SUMMONERS_RIFT_ALL_RANDOM = 325,
        /// `400`.
        /// 5v5 Draft Pick games on Summoner's Rift
        SUMMONERS_RIFT_5V5_DRAFT_PICK = 400,
        /// `410`.
        /// 5v5 Ranked Dynamic games on Summoner's Rift
        ///
        /// Game mode deprecated in patch 6.22
        #[deprecated(note="Game mode deprecated in patch 6.22")]
        SUMMONERS_RIFT_5V5_RANKED_DYNAMIC = 410,
        /// `420`.
        /// 5v5 Ranked Solo games on Summoner's Rift
        SUMMONERS_RIFT_5V5_RANKED_SOLO = 420,
        /// `430`.
        /// 5v5 Blind Pick games on Summoner's Rift
        SUMMONERS_RIFT_5V5_BLIND_PICK = 430,
        /// `440`.
        /// 5v5 Ranked Flex games on Summoner's Rift
        SUMMONERS_RIFT_5V5_RANKED_FLEX = 440,
        /// `450`.
        /// 5v5 ARAM games on Howling Abyss
        HOWLING_ABYSS_5V5_ARAM = 450,
        /// `460`.
        /// 3v3 Blind Pick games on Twisted Treeline
        ///
        /// Deprecated in patch 9.23
        #[deprecated(note="Deprecated in patch 9.23")]
        TWISTED_TREELINE_3V3_BLIND_PICK = 460,
        /// `470`.
        /// 3v3 Ranked Flex games on Twisted Treeline
        ///
        /// Deprecated in patch 9.23
        #[deprecated(note="Deprecated in patch 9.23")]
        TWISTED_TREELINE_3V3_RANKED_FLEX_DEPRECATED_470 = 470,
        /// `480`.
        /// Normal (Swiftplay) games on Summoner's Rift
        SUMMONERS_RIFT_NORMAL_SWIFTPLAY = 480,
        /// `490`.
        /// Normal (Quickplay) games on Summoner's Rift
        SUMMONERS_RIFT_NORMAL_QUICKPLAY = 490,
        /// `600`.
        /// Blood Hunt Assassin games on Summoner's Rift
        SUMMONERS_RIFT_BLOOD_HUNT_ASSASSIN = 600,
        /// `610`.
        /// Dark Star: Singularity games on Cosmic Ruins
        COSMIC_RUINS_DARK_STAR_SINGULARITY = 610,
        /// `700`.
        /// Summoner's Rift Clash games on Summoner's Rift
        SUMMONERS_RIFT_CLASH = 700,
        /// `720`.
        /// ARAM Clash games on Howling Abyss
        HOWLING_ABYSS_ARAM_CLASH = 720,
        /// `800`.
        /// Co-op vs. AI Intermediate Bot games on Twisted Treeline
        ///
        /// Deprecated in patch 9.23
        #[deprecated(note="Deprecated in patch 9.23")]
        TWISTED_TREELINE_CO_OP_VS_AI_INTERMEDIATE_BOT = 800,
        /// `810`.
        /// Co-op vs. AI Intro Bot games on Twisted Treeline
        ///
        /// Deprecated in patch 9.23
        #[deprecated(note="Deprecated in patch 9.23")]
        TWISTED_TREELINE_CO_OP_VS_AI_INTRO_BOT = 810,
        /// `820`.
        /// Co-op vs. AI Beginner Bot games on Twisted Treeline
        TWISTED_TREELINE_CO_OP_VS_AI_BEGINNER_BOT = 820,
        /// `830`.
        /// Co-op vs. AI Intro Bot games on Summoner's Rift
        ///
        /// Deprecated in March 2024 in favor of queueId 870
        #[deprecated(note="Deprecated in March 2024 in favor of queueId 870")]
        SUMMONERS_RIFT_CO_OP_VS_AI_INTRO_BOT_DEPRECATED_830 = 830,
        /// `840`.
        /// Co-op vs. AI Beginner Bot games on Summoner's Rift
        ///
        /// Deprecated in March 2024 in favor of queueId 880
        #[deprecated(note="Deprecated in March 2024 in favor of queueId 880")]
        SUMMONERS_RIFT_CO_OP_VS_AI_BEGINNER_BOT_DEPRECATED_840 = 840,
        /// `850`.
        /// Co-op vs. AI Intermediate Bot games on Summoner's Rift
        ///
        /// Deprecated in March 2024 in favor of queueId 890
        #[deprecated(note="Deprecated in March 2024 in favor of queueId 890")]
        SUMMONERS_RIFT_CO_OP_VS_AI_INTERMEDIATE_BOT_DEPRECATED_850 = 850,
        /// `870`.
        /// Co-op vs. AI Intro Bot games on Summoner's Rift
        SUMMONERS_RIFT_CO_OP_VS_AI_INTRO_BOT = 870,
        /// `880`.
        /// Co-op vs. AI Beginner Bot games on Summoner's Rift
        SUMMONERS_RIFT_CO_OP_VS_AI_BEGINNER_BOT = 880,
        /// `890`.
        /// Co-op vs. AI Intermediate Bot games on Summoner's Rift
        SUMMONERS_RIFT_CO_OP_VS_AI_INTERMEDIATE_BOT = 890,
        /// `900`.
        /// ARURF games on Summoner's Rift
        SUMMONERS_RIFT_ARURF = 900,
        /// `910`.
        /// Ascension games on Crystal Scar
        CRYSTAL_SCAR_ASCENSION = 910,
        /// `920`.
        /// Legend of the Poro King games on Howling Abyss
        HOWLING_ABYSS_LEGEND_OF_THE_PORO_KING = 920,
        /// `940`.
        /// Nexus Siege games on Summoner's Rift
        SUMMONERS_RIFT_NEXUS_SIEGE = 940,
        /// `950`.
        /// Doom Bots Voting games on Summoner's Rift
        SUMMONERS_RIFT_DOOM_BOTS_VOTING = 950,
        /// `960`.
        /// Doom Bots Standard games on Summoner's Rift
        SUMMONERS_RIFT_DOOM_BOTS_STANDARD = 960,
        /// `980`.
        /// Star Guardian Invasion: Normal games on Valoran City Park
        VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_NORMAL = 980,
        /// `990`.
        /// Star Guardian Invasion: Onslaught games on Valoran City Park
        VALORAN_CITY_PARK_STAR_GUARDIAN_INVASION_ONSLAUGHT = 990,
        /// `1000`.
        /// PROJECT: Hunters games on Overcharge
        OVERCHARGE_PROJECT_HUNTERS = 1000,
        /// `1010`.
        /// Snow ARURF games on Summoner's Rift
        SUMMONERS_RIFT_SNOW_ARURF = 1010,
        /// `1020`.
        /// One for All games on Summoner's Rift
        SUMMONERS_RIFT_ONE_FOR_ALL = 1020,
        /// `1030`.
        /// Odyssey Extraction: Intro games on Crash Site
        CRASH_SITE_ODYSSEY_EXTRACTION_INTRO = 1030,
        /// `1040`.
        /// Odyssey Extraction: Cadet games on Crash Site
        CRASH_SITE_ODYSSEY_EXTRACTION_CADET = 1040,
        /// `1050`.
        /// Odyssey Extraction: Crewmember games on Crash Site
        CRASH_SITE_ODYSSEY_EXTRACTION_CREWMEMBER = 1050,
        /// `1060`.
        /// Odyssey Extraction: Captain games on Crash Site
        CRASH_SITE_ODYSSEY_EXTRACTION_CAPTAIN = 1060,
        /// `1070`.
        /// Odyssey Extraction: Onslaught games on Crash Site
        CRASH_SITE_ODYSSEY_EXTRACTION_ONSLAUGHT = 1070,
        /// `1090`.
        /// Teamfight Tactics games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS = 1090,
        /// `1091`.
        /// Teamfight Tactics 1v0 games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_1V0 = 1091,
        /// `1092`.
        /// Teamfight Tactics 2v0 games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_2V0 = 1092,
        /// `1100`.
        /// Ranked Teamfight Tactics games on Convergence
        CONVERGENCE_RANKED_TEAMFIGHT_TACTICS = 1100,
        /// `1110`.
        /// Teamfight Tactics Tutorial games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_TUTORIAL = 1110,
        /// `1111`.
        /// Teamfight Tactics Simluation games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_SIMLUATION = 1111,
        /// `1130`.
        /// Ranked Teamfight Tactics (Hyper Roll) games on Convergence
        CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_HYPER_ROLL = 1130,
        /// `1150`.
        /// Ranked Teamfight Tactics (Double Up Workshop) games on Convergence
        ///
        /// Deprecated in patch 12.11 in favor of queueId 1160
        #[deprecated(note="Deprecated in patch 12.11 in favor of queueId 1160")]
        CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_DEPRECATED_1150 = 1150,
        /// `1160`.
        /// Ranked Teamfight Tactics (Double Up Workshop) games on Convergence
        CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP = 1160,
        /// `1200`.
        /// Nexus Blitz games on Nexus Blitz
        ///
        /// Deprecated in patch 9.2 in favor of queueId 1300
        #[deprecated(note="Deprecated in patch 9.2 in favor of queueId 1300")]
        NEXUS_BLITZ_DEPRECATED_1200 = 1200,
        /// `1210`.
        /// Teamfight Tactics (Choncc's Treasure) games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_CHONCCS_TREASURE = 1210,
        /// `1300`.
        /// Nexus Blitz games on Nexus Blitz
        NEXUS_BLITZ = 1300,
        /// `1400`.
        /// Ultimate Spellbook games on Summoner's Rift
        SUMMONERS_RIFT_ULTIMATE_SPELLBOOK = 1400,
        /// `1700`.
        /// 2v2v2v2 `CHERRY` games on Arena
        ARENA_2V2V2V2_CHERRY = 1700,
        /// `1710`.
        /// Arena (`CHERRY` games) games on Rings of Wrath
        RINGS_OF_WRATH_ARENA_CHERRY_GAMES = 1710,
        /// `1810`.
        /// Swarm solo (`STRAWBERRY` games) games on Swarm
        SWARM_SOLO_STRAWBERRY_GAMES = 1810,
        /// `1820`.
        /// Swarm duo (`STRAWBERRY` games) games on Swarm
        SWARM_DUO_STRAWBERRY_GAMES = 1820,
        /// `1830`.
        /// Swarm trio (`STRAWBERRY` games) games on Swarm
        SWARM_TRIO_STRAWBERRY_GAMES = 1830,
        /// `1840`.
        /// Swarm quad (`STRAWBERRY` games) games on Swarm
        SWARM_QUAD_STRAWBERRY_GAMES = 1840,
        /// `1900`.
        /// Pick URF games on Summoner's Rift
        SUMMONERS_RIFT_PICK_URF = 1900,
        /// `2000`.
        /// Tutorial 1 games on Summoner's Rift
        SUMMONERS_RIFT_TUTORIAL_1 = 2000,
        /// `2010`.
        /// Tutorial 2 games on Summoner's Rift
        SUMMONERS_RIFT_TUTORIAL_2 = 2010,
        /// `2020`.
        /// Tutorial 3 games on Summoner's Rift
        SUMMONERS_RIFT_TUTORIAL_3 = 2020,
        /// `6000`.
        /// Teamfight Tactics Set 3.5 Revival games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_SET_3_5_REVIVAL = 6000,
        /// `6100`.
        /// Teamfight Tactics Revival: Festival of Beasts games on Convergence
        CONVERGENCE_TEAMFIGHT_TACTICS_REVIVAL_FESTIVAL_OF_BEASTS = 6100,
    }
}
