name: CI

on:
  push:
    branches: [v/2.x.x]
  pull_request:
    branches: [v/2.x.x]
  schedule:
    - cron: "24 05 * * *" # Daily at 10:24 PM PDT, 9:24 PM PST.
  workflow_dispatch:
# TODO: generate nightly releases
#    inputs:
#      should_bench:
#        description: "Should Benchmark? (`true`)"
#        required: true
#        default: "false"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          cancel_others: "true"

  test:
    name: Check & Test
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      RGAPI_KEY: ${{ secrets.RGAPI_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo +stable check --all-targets --features riven/__proxy
      - run: cargo +stable check --all-targets --features riven/tracing,riven/__proxy
      - run: cargo check --all-targets --features riven/nightly,riven/tracing,riven/__proxy
      - run: cargo build --all-targets --features riven/nightly,riven/deny-unknown,riven/eserde,riven/__proxy
      - run: cargo test --no-fail-fast --features riven/nightly,riven/deny-unknown,riven/eserde,riven/__proxy
      - name: Install `wasm-pack`
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --node -- --features riven/nightly,riven/deny-unknown,riven/eserde
        working-directory: riven

  lints:
    name: Lints
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  doc:
    name: Docs
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs -p riven

  msrv:
    name: Verify MSRV
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-msrv --no-default-features
      - run: cargo msrv verify --path riven
